theme: jekyll-theme-minimal
title: MSOMS - Film Metamorphosis: from silent to ....?
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
