# # External plugins
# # See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
# plugins:
#   - jekyll-archives # Sorry, not GitHub pages friendly!
#   - jekyll-sitemap
#   - jekyll-paginate-v2

# exclude:
#   - "/vendor/"

# # Site settings
# title: Let's talk about movies
# subtitle: "It's time to tell a story"
# email: blcentra@gmail.com
# name: Melanie Brtan
# description: >
#   A simple yet classy theme for your Jekyll website or blog.
# # Base URL of site (i.e. /blog). It should always start with a slash,
# # and never end with a slash. Set it to a blank value if hosting at the
# # root of your server.
# cover: "/assets/James-Bond-No-Time-To-Die-OMEGA-Filmplakat.jpg"
# logo: "/assets/logo.png"

# # Build settings
# markdown: kramdown
# inter_post_navigation: false
# highlightjs_theme: "monokai-sublime"

# # Pagination Settings
# # https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
# pagination:
#   enabled: false
#   per_page: 5
#   permalink: "/page/:num/"
#   sort_reverse: 
  

# # Archive settings (see https://github.com/jekyll/jekyll-archives/)
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layout: 'archive'
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'
